WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pilot:
            type: string
            length: 255
            nullable: true
        freeSeats:
            type: integer
            nullable: true
        takeOfTime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
            departure:
                targetEntity: WCS\CoavBundle\Entity\Terrain
                inversedBy: departures
            arrival:
                targetEntity: WCS\CoavBundle\Entity\Terrain
                inversedBy: arrivals
            plane:
                targetEntity: WCS\CoavBundle\Entity\PlaneModel
