WCS\CoavBundle\Entity\Terrain:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\TerrainRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        icao:
            type: string
            length: '4'
        lattitue:
            type: float
        longitude:
            type: float
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    oneToMany:
        arrivals:
             targetEntity: WCS\CoavBundle\Entity\Flight
             mappedBy: arrival
        departures:
             targetEntity: WCS\CoavBundle\Entity\Flight
             mappedBy: departure
